name: Build Windows Installer

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.6'
        channel: 'stable'
        
    - name: Enable Windows desktop
      run: flutter config --enable-windows-desktop
      
    - name: Install dependencies
      run: flutter pub get
      
    - name: Build Windows app
      run: flutter build windows --release
      
    - name: Setup NSIS
      uses: joncloud/makensis-action@v4
      
    - name: Create installer script
      run: |
        $content = @'
        !define APP_NAME "鸿蒙HAP安装助手"
        !define APP_VERSION "1.0.0"
        !define PUBLISHER "Dossen"
        !define WEB_SITE "https://github.com/your-username/hap_assistant"
        !define APP_EXE "hap_assistant.exe"
        !define INSTALL_DIR "$PROGRAMFILES\${APP_NAME}"
        
        Name "${APP_NAME}"
        OutFile "HAP_Assistant_Setup.exe"
        InstallDir "${INSTALL_DIR}"
        RequestExecutionLevel admin
        
        !include "MUI2.nsh"
        
        !define MUI_ABORTWARNING
        !define MUI_ICON "${NSISDIR}\Contrib\Graphics\Icons\modern-install.ico"
        !define MUI_UNICON "${NSISDIR}\Contrib\Graphics\Icons\modern-uninstall.ico"
        
        !insertmacro MUI_PAGE_WELCOME
        !insertmacro MUI_PAGE_LICENSE "LICENSE"
        !insertmacro MUI_PAGE_DIRECTORY
        !insertmacro MUI_PAGE_INSTFILES
        !insertmacro MUI_PAGE_FINISH
        
        !insertmacro MUI_UNPAGE_WELCOME
        !insertmacro MUI_UNPAGE_CONFIRM
        !insertmacro MUI_UNPAGE_INSTFILES
        !insertmacro MUI_UNPAGE_FINISH
        
        !insertmacro MUI_LANGUAGE "SimpChinese"
        
        Section "MainSection" SEC01
          SetOutPath "$INSTDIR"
          SetOverwrite ifnewer
          
          File /r "build\windows\x64\runner\Release\*"
          
          CreateDirectory "$SMPROGRAMS\${APP_NAME}"
          CreateShortCut "$SMPROGRAMS\${APP_NAME}\${APP_NAME}.lnk" "$INSTDIR\${APP_EXE}"
          CreateShortCut "$DESKTOP\${APP_NAME}.lnk" "$INSTDIR\${APP_EXE}"
          
          WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_NAME}" "DisplayName" "${APP_NAME}"
          WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_NAME}" "UninstallString" "$INSTDIR\uninstall.exe"
          WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_NAME}" "DisplayIcon" "$INSTDIR\${APP_EXE}"
          WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_NAME}" "Publisher" "${PUBLISHER}"
          WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_NAME}" "URLInfoAbout" "${WEB_SITE}"
          WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_NAME}" "DisplayVersion" "${APP_VERSION}"
          WriteRegDWORD HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_NAME}" "NoModify" 1
          WriteRegDWORD HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_NAME}" "NoRepair" 1
          
          WriteUninstaller "$INSTDIR\uninstall.exe"
        SectionEnd
        
        Section "Uninstall"
          Delete "$INSTDIR\uninstall.exe"
          Delete "$INSTDIR\${APP_EXE}"
          RMDir /r "$INSTDIR"
          
          Delete "$SMPROGRAMS\${APP_NAME}\${APP_NAME}.lnk"
          RMDir "$SMPROGRAMS\${APP_NAME}"
          Delete "$DESKTOP\${APP_NAME}.lnk"
          
          DeleteRegKey HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_NAME}"
        SectionEnd
        '@
        $content | Out-File -FilePath "installer.nsi" -Encoding UTF8
      shell: powershell
      
    - name: Create LICENSE file
      run: |
        $license = @'
        MIT License
        
        Copyright (c) 2024 Dossen
        
        Permission is hereby granted, free of charge, to any person obtaining a copy
        of this software and associated documentation files (the "Software"), to deal
        in the Software without restriction, including without limitation the rights
        to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        copies of the Software, and to permit persons to whom the Software is
        furnished to do so, subject to the following conditions:
        
        The above copyright notice and this permission notice shall be included in all
        copies or substantial portions of the Software.
        
        THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
        IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
        FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
        AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
        LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
        OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
        SOFTWARE.
        '@
        $license | Out-File -FilePath "LICENSE" -Encoding UTF8
      shell: powershell
      
    - name: Build installer
      run: makensis installer.nsi
      
    - name: Upload installer artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-installer
        path: HAP_Assistant_Setup.exe
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: HAP_Assistant_Setup.exe
        name: Release ${{ github.ref_name }}
        body: |
          ## 鸿蒙HAP安装助手 ${{ github.ref_name }}
          
          ### 新功能
          - Windows安装包自动构建
          - 简化的应用图标设计
          - HAP文件安装功能
          
          ### 安装说明
          1. 下载 `HAP_Assistant_Setup.exe`
          2. 以管理员权限运行安装程序
          3. 按照安装向导完成安装
          
          ### 系统要求
          - Windows 10 或更高版本
          - 64位操作系统
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}