name: Build Windows Installer

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.6'
        channel: 'stable'
        
    - name: Enable Windows desktop
      run: flutter config --enable-windows-desktop
      
    - name: Install dependencies
      run: flutter pub get
      
    - name: Build Windows app
      run: flutter build windows --release
      
    - name: Upload Windows executable
      uses: actions/upload-artifact@v4
      with:
        name: windows-executable
        path: build/windows/x64/runner/Release/
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: build/windows/x64/runner/Release/hap_assistant.exe
        name: Release ${{ github.ref_name }}
        body: |
          ## 鸿蒙HAP安装助手 ${{ github.ref_name }}
          
          ### 新功能
          - Windows可执行文件自动构建
          - 简化的应用图标设计
          - HAP文件安装功能
          
          ### 使用说明
          1. 下载 `hap_assistant.exe`
          2. 直接运行可执行文件
          3. 无需安装，绿色便携
          
          ### 系统要求
          - Windows 10 或更高版本
          - 64位操作系统
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}