name: Build Windows Installer

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      create_release:
        description: '是否创建Release'
        required: true
        default: 'true'
        type: choice
        options:
        - 'true'
        - 'false'

permissions:
  contents: write
  packages: write
  pull-requests: read

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.6'
        channel: 'stable'
        
    - name: Enable Windows desktop
      run: flutter config --enable-windows-desktop
      
    - name: Install dependencies
      run: flutter pub get
      
    - name: Build Windows app
      run: flutter build windows --release
      
    - name: Create Portable Package
      run: |
        mkdir package
        xcopy "build\windows\x64\runner\Release\*" "package\" /E /I
        
    - name: Create Single File Package
      run: |
        mkdir single-file
        copy "build\windows\x64\runner\Release\hap_assistant.exe" "single-file\"
        copy "build\windows\x64\runner\Release\flutter_windows.dll" "single-file\"
        
    # MSIX Package creation removed to avoid configuration issues
        
    - name: Upload Portable Package
      uses: actions/upload-artifact@v4
      with:
        name: windows-portable-package
        path: package/
        
    - name: Upload Single File Package
      uses: actions/upload-artifact@v4
      with:
        name: windows-single-file
        path: single-file/
        
    # MSIX Package upload removed
        
    - name: Set Release Tag
      if: startsWith(github.ref, 'refs/tags/') || (github.event_name == 'workflow_dispatch' && github.event.inputs.create_release == 'true')
      id: set_tag
      run: |
        if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          echo "tag=v$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT
        else
          echo "tag=${{ github.ref_name }}" >> $GITHUB_OUTPUT
        fi
      shell: bash
        
    - name: Create Release Packages
      if: startsWith(github.ref, 'refs/tags/') || (github.event_name == 'workflow_dispatch' && github.event.inputs.create_release == 'true')
      run: |
        cd package
        tar -czf ../hap_assistant_windows_portable_${{ steps.set_tag.outputs.tag }}.tar.gz *
        cd ../single-file
        tar -czf ../hap_assistant_windows_single_${{ steps.set_tag.outputs.tag }}.tar.gz *
        cd ..
        # MSIX package creation removed
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/') || (github.event_name == 'workflow_dispatch' && github.event.inputs.create_release == 'true')
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          hap_assistant_windows_portable_${{ steps.set_tag.outputs.tag }}.tar.gz
          hap_assistant_windows_single_${{ steps.set_tag.outputs.tag }}.tar.gz
        name: Release ${{ steps.set_tag.outputs.tag }}
        tag_name: ${{ steps.set_tag.outputs.tag }}
        body: |
          ## 鸿蒙HAP安装助手 ${{ steps.set_tag.outputs.tag }}
          
          ### 新功能
          - 优化Windows和macOS共享文件夹连接方式
          - 提供三种Windows打包格式
          - 增强错误处理和用户交互
          - 支持多平台文件路径格式
          
          ### Windows版本说明
          
          #### 1. 便携版 (Portable)
          - 文件: `hap_assistant_windows_portable_${{ steps.set_tag.outputs.tag }}.tar.gz`
          - 包含完整的运行环境和依赖库
          - 解压即用，无需安装
          - 适合临时使用或无管理员权限的环境
          
          #### 2. 精简版 (Single File)
          - 文件: `hap_assistant_windows_single_${{ steps.set_tag.outputs.tag }}.tar.gz`
          - 仅包含核心可执行文件
          - 体积更小，启动更快
          - 需要系统已安装Visual C++运行库
          
          #### 注意事项
          - 便携版包含完整运行环境，推荐使用
          - 精简版需要系统预装Visual C++运行库
          - 两个版本都支持Windows 10及以上系统
          
          ### 共享文件夹连接优化
          - **Windows**: 支持UNC路径 (`\\IP\共享文件夹\路径`)
          - **macOS**: 支持SMB协议 (`smb://IP/共享文件夹/路径`)
          - **Linux**: 支持标准网络路径 (`//IP/共享文件夹/路径`)
          - 自动路径格式转换和错误处理
          
          ### 系统要求
          - Windows 10 或更高版本
          - 64位操作系统
          - .NET Framework 4.7.2+ (精简版需要)