name: Build Windows Installer

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.6'
        channel: 'stable'
        
    - name: Enable Windows desktop
      run: flutter config --enable-windows-desktop
      
    - name: Install dependencies
      run: flutter pub get
      
    - name: Build Windows app
      run: flutter build windows --release
      
    - name: Create Windows Package
      run: |
        mkdir package
        xcopy "build\windows\x64\runner\Release\*" "package\" /E /I
        
    - name: Upload Windows Package
      uses: actions/upload-artifact@v4
      with:
        name: windows-package
        path: package/
        
    - name: Create Release Package
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        cd package
        tar -czf ../hap_assistant_windows_${{ github.ref_name }}.tar.gz *
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: hap_assistant_windows_${{ github.ref_name }}.tar.gz
        name: Release ${{ github.ref_name }}
        body: |
          ## 鸿蒙HAP安装助手 ${{ github.ref_name }}
          
          ### 新功能
          - Windows完整安装包自动构建
          - 包含所有必需的依赖库
          - 简化的应用图标设计
          - HAP文件安装功能
          
          ### 使用说明
          1. 下载 `hap_assistant_windows_${{ github.ref_name }}.tar.gz`
          2. 解压到任意目录
          3. 运行 `hap_assistant.exe`
          4. 确保所有文件保持在同一目录结构中
          
          ### 包含文件
          - `hap_assistant.exe` - 主程序
          - `flutter_windows.dll` - Flutter运行时库
          - `data/` - 应用数据和资源文件
          
          ### 系统要求
          - Windows 10 或更高版本
          - 64位操作系统
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}